on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ myenv.FTP_SERVERURL }}
        port: ${{ myenv.FTP_PORT }}
        username: ${{ myenv.FTP_USERNAME }}
        password: ${{ myenv.FTP_PASSWORD }}
        protocol: ftps
        server-dir: public
