name: Build do Site da Semac

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build the project
        run: npm run build

      - name: List files after build
        run: ls -la ./dist  

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist 
  
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: List files after download
        run: ls -la ./dist 

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 200.129.241.66
          port: 12251
          username: semac_ftp_graciely
          password: xqDCq!SfMy4bH
          protocol: ftps  
          local-dir: ./dist/  
          server-dir: ./  